import jsPDF from "jspdf";

export const downloadPDF = (title: string, content: string) => {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  let cursorY = 20;

  // --- HEADER ---
  // Company/Tool Branding (Watermark style top right)
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by Job Tuner", pageWidth - 60, 15);

  // Job Title (Main Header)
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(33, 37, 41); // Dark Slate
  
  const splitTitle = doc.splitTextToSize(title || "Untitled Role", 170);
  doc.text(splitTitle, 20, cursorY + 10);
  cursorY += (splitTitle.length * 10) + 15;

  // Separator Line
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(20, cursorY, pageWidth - 20, cursorY);
  cursorY += 15;

  // --- BODY CONTENT ---
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);

  const splitText = doc.splitTextToSize(content, 170);

  splitText.forEach((line: string) => {
    // Check for page break
    if (cursorY > pageHeight - 25) {
      doc.addPage();
      cursorY = 20;
      // Re-add watermark on new pages
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text("Generated by Job Tuner", pageWidth - 60, 15);
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
    }
    doc.text(line, 20, cursorY);
    cursorY += 6; 
  });

  // --- FOOTER ---
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(180);
    doc.text(`Page ${i} of ${pageCount} | Professional Hiring Document`, 20, pageHeight - 10);
  }

  doc.save(`${title.replace(/\s+/g, '_')}_JD.pdf`);
};

export const shareViaEmail = (title: string, content: string) => {
  const subject = encodeURIComponent(`Job Description: ${title}`);
  const body = encodeURIComponent(`Here is the job description for ${title}:\n\n${content}`);
  window.location.href = `mailto:?subject=${subject}&body=${body}`;
};